version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./build.php:/var/www/html/index.php
    depends_on:
      - php

  php:
    image: php:8.3-fpm
    volumes:
      - ./build.php:/var/www/html/index.php
