version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./build.php:/var/www/html/index.php
    depends_on:
      - php
    networks:
      - php-encryption

  php:
    image: php:${TARGET_PHP_VERSION}-fpm
    volumes:
      - ./build.php:/var/www/html/index.php
    depends_on:
      - builder
    networks:
      - php-encryption

  builder:
    image: xosh/php-source-encryption-builder:latest
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./test.php:/app/index.php
      - ./build.php:/app/build.php

networks:
  php-encryption:
